### ISSUE TITLE
Sleeper

### ISSUE THREAD

**Issue by JustinPhlegar** [Orasi/JS-Selenium-Toolkit#4]
[Wiki Page](https://github.com/Orasi/Selenium-Java-Core/wiki/Sleeper.java)
[Original Source](https://github.com/Orasi/Selenium-Java-Core/blob/master/src/main/java/com/orasi/utils/Sleeper.java)

In java, the why to pause the script is to stop the thread for a certain about of milliseconds, similar to UFT wait statements. The pause length is determined by the OS, so a pause for 3 seconds might be 3 seconds on a linux machine, but 4.5 seconds on a win7 machine. Also, it require the process of catching exceptions which made scripting very untidy.

Research to how NodeJS will pause the script is needed. It is possible a Sleeper method may not even be required as it may already have a built in sleep

**Comment by Grimlek** [comment]
Node is asynchronous by nature, and that's what's great about it, so we really shouldn't be blocking the thread but instead blocking requests. It uses a single thread of execution so it can only be computing one request at a time, but could have events pending on many requests in a queue. SetTimeout can be used to block events or requests, it stores the event in the queue and can then begin executing the next request. The next request may be several lines of code farther down the script where the thread doesn't have to wait for data. The thread may not have another request/event and therefore will wait for an event/request. Whenever the timer ends on the setTimeout function the thread will return to the request for execution.

Here is an introduction video:
http://nodecasts.net/episodes/1-introduction-to-nodejs

**Comment by Grimlek** [comment]
selenium-webdriver has sleep(milliseconds) as a function for the object, this will stop the driver.

**Comment by JustinPhlegar** [comment]
Something to consider, we need a way of pausing the script, outside of webdriver. Since the toolkit allows for more than just browser automation, the webdriver sleeps would not work there.

We can make it NodeJS best practice to use the Webdriver sleeps, but we just need a second option outside of WebDriver.
